server:
  port: 8071
spring:
  application:
    name: service-a
  sleuth:
    web:
      enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: kafka
  # kafka集群地址
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      retries: 3
logging:
  config: classpath:logback/logback.xml

# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
